### ISSUE TITLE
No output from CameraControl

### ISSUE THREAD

**Issue by markmac99** [CroatianMeteorNetwork/RMS#692]
On 28/07 R Bassom reported that the CameraControl module was broken and not producing any output. Investigation revealed that this seems to be an unintended side effect of changes to the logger which now suppresses console output by default. I've raised a PR to fix this for CameraControl but other standalone modules are likely to be affected.

**Comment by g7gpr** [comment]
Is everything getting printed and logged now? I'm seeing some strange things on master.

```
2025/07/29 01:36:10-INFO-EventMonitor-line:2144 - Next EventMonitor run : 02:06:10 UTC; 30.0 minutes from now
2025/07/29 01:36:10-INFO-EventMonitor-line:2148 - Next Capture start    : 07:42:48 UTC
Next EventMonitor run : 02:36:11 UTC; 30.0 minutes from now
Next Capture start    : 07:42:48 UTC
2025/07/29 02:06:11-INFO-EventMonitor-line:2144 - Next EventMonitor run : 02:36:11 UTC; 30.0 minutes from now
2025/07/29 02:06:11-INFO-EventMonitor-line:2148 - Next Capture start    : 07:42:48 UTC
Next EventMonitor run : 03:06:13 UTC; 30.0 minutes from now
Next Capture start    : 07:42:48 UTC
2025/07/29 02:36:13-INFO-EventMonitor-line:2144 - Next EventMonitor run : 03:06:13 UTC; 30.0 minutes from now
2025/07/29 02:36:13-INFO-EventMonitor-line:2148 - Next Capture start    : 07:42:48 UTC
Next EventMonitor run : 03:36:15 UTC; 30.0 minutes from now
Next Capture start    : 07:42:48 UTC
2025/07/29 03:06:15-INFO-EventMonitor-line:2144 - Next EventMonitor run : 03:36:15 UTC; 30.0 minutes from now
2025/07/29 03:06:15-INFO-EventMonitor-line:2148 - Next Capture start    : 07:42:48 UTC
```

**Comment by dvida** [comment]
Hmm, it's only supposed to be for CameraControl. I see the issue, I undid the PR for now. Let's think about this one a bit more.

**Comment by Cybis320** [comment]
CameraControl has been working fine for me. Can we get more details as to what the problem is and steps to reproduce?
```
vRMS) ops@procamsff02:~/source/RMS$ python -m Utils.CameraControl SetParam Camera DayNightColor 2
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
Creating directory: /home/ops/RMS_data
   Success: True
Creating directory: /home/ops/RMS_data/logs
   Success: True
2025/07/29 04:09:30-DEBUG-Logger-line:371 - Log listener configured. Current file: /home/ops/RMS_data/logs/camControl_log_XX0002_20250729_040930.log
2025/07/29 04:09:30-DEBUG-Logger-line:495 - initLogging completed; queue listener started.
2025/07/29 04:09:31-INFO-CameraControl-line:515 - Set Camera.Param.[0].DayNightColor to 0x00000002
```

**Comment by Cybis320** [comment]
Here was the output from a year-old version:
```
(vRMS) ops@procamsff02:~/source/RMS$ python -m Utils.CameraControl SetParam Camera ElecLevel 60
Loading the default config!
Set Camera.Param.[0].ElecLevel to 60
```

Here's the current output:
```
2025/07/29 04:38:36-INFO-CameraControl-line:515 - Set Camera.Param.[0].ElecLevel to 60
Shutting down logging...
Logging shutdown complete.
```
Both versions apply the setting correctly.

**Comment by Cybis320** [comment]
I'm not sure why we are logging in standalone.
If we remove these line in __main__, we are back to the simple output from before the recent updates:
https://github.com/CroatianMeteorNetwork/RMS/blob/77be7528c3f8e117e80c3f104cf2e5386a9b41c9/Utils/CameraControl.py#L920-L921

**Comment by markmac99** [comment]
@Cybis320  ref your first, it works corretly only if you are in ~/source/RMS when you run it. It malfunctions for multicam and if you run it anywhere outside ~/source/RMS on Pi. As you will be aware, when you pass the -c parameter to other modules, they run correctly, reading the config file as needed, and in any events this is a breaking change so should be fixed. 

Ref your 2nd, the problem is that the end user has no way to know if its worked because there's no output on screen!  

Ref your last, i  believe you added logging on 15/April, presumably to get some logging output when called from SwitchCameraModes(). I agree its not necessary in this module when called standalone.

**Comment by dvida** [comment]
Thank you for the detailed breakdown - do you want me to remove those two lines then? I'm ok with that.

**Comment by Cybis320** [comment]
I still don't understand the issue. What's not working and what's breaking exactly? What exact command used to work and now doesn’t, and what is the output?

Here's what I'm seeing on my side:
```
(vRMS) bolide@EliteCam01:~/source/RMS$ python -m Utils.CameraControl SetParam Camera DayNightColor 1 -c ~/source/Stations/US005B/.config
Loading config file: /home/bolide/source/Stations/US005B/.config
Creating directory: /home/bolide/RMS_data/US005B
   Success: True
Creating directory: /home/bolide/RMS_data/US005B/logs
   Success: True
2025/07/31 22:29:24-INFO-CameraControl-line:515 - Set Camera.Param.[0].DayNightColor to 0x00000001
Shutting down logging...
Logging shutdown complete.
```

**Comment by markmac99** [comment]
As i have explained several times, if you run this from any location other than ~/source/RMS, there is no output of the actual expected data, in this case the hostname. The only output is some unnecesssary logging of folder creation. 

```
**(vRMS) rms@ubunturms:~/source/RMS$ cd ~/source/Stations/UK0006**
(vRMS) rms@ubunturms:~/source/Stations/UK0006$ python -m Utils.CameraControl GetHostname
Loading the default config!
Creating directory: /home/rms/RMS_data/UK0006
   Success: True
Creating directory: /home/rms/RMS_data/UK0006/logs
   Success: True
(vRMS) rms@ubunturms:~/source/Stations/UK0006$
```
or 
```
(vRMS) rms@ubunturms:~/source/Stations/UK0006$ python -m Utils.CameraControl GetHostname -c ./.config
Loading config file: /home/rms/source/Stations/UK0006/.config
Creating directory: /home/rms/RMS_data/UK0006
   Success: True
Creating directory: /home/rms/RMS_data/UK0006/logs
   Success: True
(vRMS) rms@ubunturms:~/source/Stations/UK0006$
``

**Comment by Cybis320** [comment]
Mark, the unnecessary logging is because you added logging in the main. Your code comment says it was to silence DVRip output. DVRip output seems to be silenced without having to create a log in the main.

I see the issue is present in master and prerelease but not in alpha1 (I created a branch with most of the current fixes rolled in). I think the issue is that the logger closes early and fails to record the last outputs. alpha1 incorporates PR #684 which fixes that.

It has nothing to do with the working directory.

The immediate fix for master would be to delete the log creation in main.

Here's the output from alpha1:

```
(vRMS) ops@EliteCam01:~/source/Stations/US005B$ python -m  Utils.CameraControl GetHostname
Loading the default config!
Creating directory: /home/ops/RMS_data/US005B
   Success: True
Creating directory: /home/ops/RMS_data/US005B/logs
   Success: True
Shutting down logging...
2025/08/01 16:32:46-INFO-CameraControl-line:702 - LocalHost
Logging shutdown complete.
```

**Comment by markmac99** [comment]
@Cybis320  I'm a bit unsure what your point is.  My point was that last week, CameraControl worked properly. This week, it doesn't. I didn't change anything in this module recently and its kind of annoying that I'm being blamed for this bug.

Regarding logging, when called from other RMS code, because we are or were by default logging DEBUG messages, and because the logger had been changed to seize control of every single logger stream instantiated by any code called by RMS, DVRip's debug functionality was being triggered, leading to it including passwords and SSH keys from connections in logfiles. I sincerely hope we agree that was bad. So firstly if we could stop logging every darn debug message that'd be great. Equally if this problem has been fixed, and DVRip#s messages are no longer being logged, that too would be great. 

So TLDR, if you think you have a fix, please apply it. Happy to test.

**Comment by markmac99** [comment]
ps - I've unsubscribed from this topic, as i can offer no further input.

**Comment by Cybis320** [comment]
Closing because OP not able to provide further input. If anyone wants to reopen the issue, please provide actionable details and be patient as nobody can read minds.

**Comment by markmac99** [comment]
Reopened because the bug still exists. I appreciate this has become a heated topic, but this is an actual bug which we need to address. I appreciate Luc doesn't have time/inclination to fix it so i will do it.  

Just to reiterate, you can replicate it as follows
Open a terminal window on a station and run this 
```
(vRMS) rms@uk002f:~/source/RMS $ cd $HOME
(vRMS) rms@uk002f:~ $ python -m Utils.CameraControl -c ~/source/RMS/.config GetCameraParams
Loading config file: /home/rms/source/RMS/.config
Creating directory: /home/rms/RMS_data
   Success: True
Creating directory: /home/rms/RMS_data/logs
   Success: True
(vRMS) rms@uk002f:~ $
```
What should happen is that the camera parameters are printed to screen.  If you're in ~/source/RMS then the functionality behaves correctly, so clearly there's some hidden dependency on the source code.

**Comment by Cybis320** [comment]
Hey Mark, I'm sorry that you confused my request for more information for a lack of will to address this issue - nothing could be further from reality. If only you knew the amount of time I spent on these things...
When asked for details on specifics, you became frustrated, which makes solving this issue more difficult than it needs to be. 

Regarding CameraControl, the issue is already resolved in alpha1. Feel free to test.

The lack of output when running from the repo dir seems to be due to the premature closing of the logger. It seems to be inconsistent for me as some messages go through and some don't. The unnecessary logging is not to 'blame' here but it just happens that if the logger is disabled in standalone mode, then the logger bug doesn’t cut the messages off. Again, you didn't cause this bug. It's not even CC specific. It's a known issue which is fixed in a PR incorporated in alpha1.

Regarding the difference between running from root vs not, when run from the repo, the repo code runs. When run from any other dir, the site-package version runs. This is a side effect of the obsolete installation method RMS has been using. We're not logging messages from the site-packages if my memory serves me right, so again disabling the logger solves this issue for this specific script. Preventing RMS from running from the site-packages dir solves all other kinds of issues. This is also fixed in alpha1.

To demonstrate, try commenting out line 921 (initLogging)  in CameraControl.py in ~/vRMS/lib/python3.7/site-packages/RMS-0.1-py3.7-linux-armv7l.egg/Utils/ or equivalent dir.

This is the result with that line commented out in master or from alpha1:
```
(vRMS) ops@procamsff02:~$ python -m Utils.CameraControl -c ~/source/RMS/.config  GetCameraParams
Loading config file: /home/ops/source/RMS/.config
{'enable': False, 'level': 30}
{'AeSensitivity': 1,
 'ApertureMode': '0x00000000',
 'BLCMode': '0x00000000',
 'DayNightColor': '0x00000002',
 'Day_nfLevel': 0,
 'DncThr': 50,
 'ElecLevel': 60,
 'Eleclevel': '0x00000064',
 'EsShutter': '0x00000000',
 'ExposureParam': {'LeastTime': '0x00009C40',
                   'Level': 0,
                   'MostTime': '0x00009C40'},
 'Gain': 60,
 'GainParam': {'AutoGain': 1, 'Gain': 60},
 'IRCUTMode': 0,
 'IrcutSwap': 0,
 'Night_nfLevel': 0,
 'PictureFlip': '0x00000000',
 'PictureMirror': '0x00000000',
 'RejectFlicker': '0x00000000',
 'WhiteBalance': '0x00000002',
{'AeMeansure': 1,
 'AutomaticAdjustment': 3,
 'BroadTrends': {'AutoGain': 0, 'Gain': 50},
 'CorridorMode': 0,
 'Dis': 0,
 'ExposureTime': '0x00000100',
 'Ldc': 0,
 'LightRestrainLevel': 16,
 'LowLuxMode': 0,
 'PreventOverExpo': 1,
 'SoftPhotosensitivecontrol': 0,
 'Style': 'type1'}
```

**Comment by markmac99** [comment]
understood. I'm currently working on a couple of other things in CameraControl so i will include this fix.  I'll build some test cases so i can test on single-station, multicam and Windows. I don't have MacOS so can't test there.

**Comment by markmac99** [comment]
ps good to know that the issue of running from site-packages will be solved. This causes any amount of unexpected behaviour ! 

pps - i am going to look at building a pypi package for RMS, should be an interesting challenge but might offer some options wrt stability.

**Comment by markmac99** [comment]
ppps "If only you knew the amount of time I spent on these things..." 
I expect i do :) I spent every evening for two years building the ukmon data capture, data processing, alerting, website etc, single handed and since retiring from my day job, the amount of time i spend on opensource projects and support has only increaased. We end up putting our souls into this stuff.

**Comment by Cybis320** [comment]
> pps - i am going to look at building a pypi package for RMS, should be an interesting challenge but might offer some options wrt stability.

Excellent, please look at alpha1 which already uses pyproject.toml - the toml is really the minimum necessary to get going at this time. It would need additional information to be PyPi ready. RMS has dependencies that PyPi doesn't support (imreg_dft), has binary extensions (kit_module), Python extensions, etc. It would be a fun and challenging project!

**Comment by markmac99** [comment]
I think this is resolved by changes made to the logger, closing it for now
